language: shell
dist: bionic

os:
  - linux

services:
  - docker

script:
  - bash .github/scripts/build.bash

jobs:
  include:
    - stage: "Build & Check"
      name: "Build Docker Image"
      if: branch != master
      script: bash .github/scripts/Build.bash
    - script: bash .github/scripts/VersionCheck.bash
      name: "Check Version"
      if: branch != master

notifications:
  email: false