language: shell
dist: bionic

os:
  - linux

services:
  - docker

script:
  - |
    docker build . -t image
    docker run --name container -d -t image
    docker exec container zsh --version

notifications:
  email: false